import { loadEnv } from 'vite';

export interface GitHubRepo {
  name: string;
  nameWithOwner: string;
  url: string;
  description: string | null;
  stargazerCount: number;
}

// Load .env.local in dev mode
const env = loadEnv('', process.cwd(), 'GITHUB_TOKEN');
const GITHUB_TOKEN = env.GITHUB_TOKEN || process.env.GITHUB_TOKEN || process.env.GH_TOKEN;

const GITHUB_USERNAME = 'abien';

export async function scrapeGitHubStarsList(limit: number = 10): Promise<GitHubRepo[]> {
  try {
    // Load repo names from config file (generated by sync-github-stars script)
    const { repos } = await import('../config/github-stars-config.json', { assert: { type: 'json' } });
    
    if (!repos || repos.length === 0) {
      console.warn('[GitHub Stars] No repos found in config. Run: npm run sync-github-stars');
      return [];
    }

    console.log(`[GitHub Stars] Using ${repos.length} repos from config`);

    // Sort by starred date (most recently starred first), then apply limit
    const sorted = await sortByStarredDate(repos);

    // Fetch details for each repo from GitHub API
    return await getRepoDetails(sorted.slice(0, limit));
  } catch (error) {
    console.error('Failed to fetch GitHub starred repos:', error);
    return [];
  }
}

async function sortByStarredDate(repoNames: string[]): Promise<string[]> {
  try {
    const remaining = new Set(repoNames.map(r => r.toLowerCase()));
    const ordered: string[] = [];
    let page = 1;

    while (remaining.size > 0 && page <= 10) {
      const res = await fetch(
        `https://api.github.com/users/${GITHUB_USERNAME}/starred?per_page=100&page=${page}`,
        {
          headers: {
            'Accept': 'application/vnd.github.star+json',
            ...(GITHUB_TOKEN && { 'Authorization': `Bearer ${GITHUB_TOKEN}` }),
          },
        }
      );

      if (!res.ok) break;

      const data = await res.json();
      if (data.length === 0) break;

      for (const item of data) {
        const fullName = (item.repo?.full_name ?? '').toLowerCase();
        if (remaining.has(fullName)) {
          ordered.push(item.repo.full_name);
          remaining.delete(fullName);
        }
      }

      page++;
    }

    for (const name of repoNames) {
      if (!ordered.some(r => r.toLowerCase() === name.toLowerCase())) {
        ordered.push(name);
      }
    }

    console.log(`[GitHub Stars] Sorted ${ordered.length} repos by starred date (${page - 1} API pages)`);
    return ordered;
  } catch (error) {
    console.warn('[GitHub Stars] Failed to sort by starred date, using config order:', error);
    return repoNames;
  }
}

async function getRepoDetails(repoNames: string[]): Promise<GitHubRepo[]> {
  try {
    // Fetch repo details in parallel
    const promises = repoNames.map(repoName =>
      fetch(`https://api.github.com/repos/${repoName}`, {
        headers: {
          'Accept': 'application/vnd.github+json',
          ...(GITHUB_TOKEN && { 'Authorization': `Bearer ${GITHUB_TOKEN}` }),
        },
      })
        .then(res => res.json())
        .catch(err => {
          console.error(`Failed to fetch ${repoName}:`, err);
          return null;
        })
    );

    const responses = await Promise.all(promises);

    const repos = responses
      .filter((repo): repo is any => repo !== null && !repo.message)
      .map(repo => ({
        name: repo.name,
        nameWithOwner: repo.full_name,
        url: repo.html_url,
        description: repo.description,
        stargazerCount: repo.stargazers_count,
      }));

    console.log(`[GitHub API] Successfully fetched ${repos.length} repo details`);
    return repos;
  } catch (error) {
    console.error('Failed to fetch repo details:', error);
    return [];
  }
}
