import { loadEnv } from 'vite';

export interface GitHubRepo {
  name: string;
  nameWithOwner: string;
  url: string;
  description: string | null;
  stargazerCount: number;
}

// Load .env.local in dev mode
const env = loadEnv('', process.cwd(), 'GITHUB_TOKEN');
const GITHUB_TOKEN = env.GITHUB_TOKEN || process.env.GITHUB_TOKEN || process.env.GH_TOKEN;

export async function scrapeGitHubStarsList(limit: number = 10): Promise<GitHubRepo[]> {
  try {
    // Load repo names from config file (generated by sync-github-stars script)
    const { repos } = await import('../config/github-stars-config.json', { assert: { type: 'json' } });
    
    if (!repos || repos.length === 0) {
      console.warn('[GitHub Stars] No repos found in config. Run: npm run sync-github-stars');
      return [];
    }

    console.log(`[GitHub Stars] Using ${repos.length} repos from config`);

    // Fetch details for each repo from GitHub API
    return await getRepoDetails(repos.slice(0, limit));
  } catch (error) {
    console.error('Failed to fetch GitHub starred repos:', error);
    return [];
  }
}

async function getRepoDetails(repoNames: string[]): Promise<GitHubRepo[]> {
  try {
    // Fetch repo details in parallel
    const promises = repoNames.map(repoName =>
      fetch(`https://api.github.com/repos/${repoName}`, {
        headers: {
          'Accept': 'application/vnd.github+json',
          ...(GITHUB_TOKEN && { 'Authorization': `Bearer ${GITHUB_TOKEN}` }),
        },
      })
        .then(res => res.json())
        .catch(err => {
          console.error(`Failed to fetch ${repoName}:`, err);
          return null;
        })
    );

    const responses = await Promise.all(promises);

    const repos = responses
      .filter((repo): repo is any => repo !== null && !repo.message)
      .map(repo => ({
        name: repo.name,
        nameWithOwner: repo.full_name,
        url: repo.html_url,
        description: repo.description,
        stargazerCount: repo.stargazers_count,
      }));

    console.log(`[GitHub API] Successfully fetched ${repos.length} repo details`);
    return repos;
  } catch (error) {
    console.error('Failed to fetch repo details:', error);
    return [];
  }
}
